const fileContents = {
  "important.txt": "====================\nWELCOME TO REQUIN-V LAB\n====================\n\nPersonnel ID: [REDACTED]\nRole: Live Operations Assistant\n\nWelcome to your workstation. As part of the Requin-V team, your responsibilities include:\n\n    - Monitoring livestream AI interfaces of the experiments\n    - Logging daily operational activity\n    - Assisting in research simulations\n    - Managing communication protocols\n\nYour interface includes the following tools:\n\n    - Quick Launch: Access notes, media, terminal, and notepad\n    - Terminal: Use commands for routine checks\n    - Folders: Organize logs, reports, and project materials\n\nPlease note:\n    - Confidential projects are restricted to secure folders\n    - Always follow standard operational protocols\n    - Unauthorized tampering is strictly prohibited\n\nFor assistance, refer to the internal help documentation or contact your supervisor.\n\n====================\nEND OF INTRODUCTION\n====================",
  "notes.txt": "====================\nFROM: PROFESSOR K. VALE\nDATE: 03/14/10245\n====================\n\nTo whom it may concern,\n\nI am leaving this note to document my observations and provide guidance for the next personnel handling [Project: Rookie].\n\n- The Shark Android's AI behavioral responses are highly sensitive to prompt inputs.\n- Emotional stability is not guaranteed; do not rely on livechat synchronization.\n- The subject exhibits enhanced physical parameters under certain simulated conditions (exercise caution).\n- Logs from prior experiments are in the restricted folders; only access with authorized clearance.\n\nPlease maintain all standard protocols and report any anomalies immediately. Remember, the subject was designed for interactive livestream purposes but has demonstrated unpredictable behavior outside controlled environments.\n\nRegards,\nProfessor K. Vale\nSenior Research Scientist\n====================\nEND OF NOTE",
  "lab-report.pdf": "CONFIDENTIAL LAB REPORT\n\n(Password protected)",
  "photo.jpg": "assets/photo.jpg",
  "extra-notepad.txt": "This is a separate independent notepad window.\nFeel free to type anything here!"
};

for(let i=1;i<=8;i++){
  fileContents[`folder${i}`] = `====================\nFOLDER ${i} CONTENTS\n====================\n\nThis folder contains notes, logs, or secret codes.\nAdd anything you like here.\n\n--- END OF FOLDER ${i} ---`;
}

